import React from 'react'

import * as unistyles from '../web/services'
import { error, isServer } from '../web/utils'
import { resetServerUnistyles } from './resetServerUnistyles'

type ServerUnistylesStylesProps = {
    nonce?: string
}

/**
 * Flushes styles generated by preceding server-rendered siblings.
 *
 * Render this component after a subtree that can be delivered independently
 * from the initial document, such as a streamed or partially navigated route.
 */
export const ServerUnistylesStyles = ({ nonce }: ServerUnistylesStylesProps) => {
    if (!isServer()) {
        throw error('Server styles should only be read on the server')
    }

    const css = unistyles.services.registry.css.getStyles()

    resetServerUnistyles()

    if (!css) {
        return null
    }

    return <style nonce={nonce}>{css}</style>
}
